package com.example.webbaziraniproekt.enumerations;

public enum Sport {
    BASKETBALL,
    FOOTBALL,
    SOCCER,
    TENNIS,
    BASEBALL,
    HOCKEY,
    VOLLEYBALL,
    SWIMMING,
    GOLF,
    ATHLETICS,
    RUGBY,
    CRICKET,
    HANDBALL,
    BOXING,
    MMA, // Mixed Martial Arts
    WRESTLING,
    BADMINTON,
    TABLE_TENNIS,
    CYCLING,
    SKIING,
    SNOWBOARDING,
    FIGURE_SKATING,
    TRACK_AND_FIELD,
    ROWING,
    WATER_POLO,
    TRIATHLON,
    EQUESTRIAN,
    MOTORSPORTS,
    ARCHERY,
    FENCING,
    GYMNASTICS,
    SURFING,
    CLIMBING,
    JUDO,
    KARATE,
    TAEKWONDO,
    KUNG_FU,
    SQUASH,
    BILLIARDS,
    DARTS,
    ESPORTS // Include electronic sports
}